export const brands = [
  { name: "Airtex", logo: "/Brands/Airtex.png", description: "Airtex — німецький бренд, що спеціалізується на високоякісних водяних насосах і компонентах систем охолодження для легкових та вантажних авто." },
  { name: "Alkar", logo: "/Brands/Alkar.png", description: "Alkar — іспанський виробник дзеркал, освітлення та елементів кузова, відомий якістю продукції для спортивних і серійних авто." },
  { name: "Autofren Seinsa", logo: "/Brands/Autofren Seinsa.png", description: "Autofren Seinsa — один з найбільших світових постачальників ремкомплектів гальмівних систем, з потужним виробництвом у Європі." },
  { name: "BCGUMA", logo: "/Brands/BCGUMA.png", description: "BCGUMA — американський виробник гумотехнічних виробів, зокрема пильовиків і сальників, популярний у класичних моделях." },
  { name: "Bilstein",logo: "/Brands/Bilstein.png", description: "Bilstein — німецький лідер у виробництві преміальних амортизаторів і підвісок, широко використовується в автоспорті." },
  { name: "Bosch", logo: "/Brands/Bosch.png", description: "Bosch — глобальний концерн із Німеччини, що виробляє широкий спектр автозапчастин: від електроніки до гальмівних систем." },
  { name: "Brembo", logo: "/Brands/BREMBO.webp", description: "Brembo — італійський бренд №1 у сфері гальмівних систем, використовується в преміальних і спортивних авто." },
  { name: "CARGO", logo: "/Brands/CARGO.png", description: "CARGO — спеціалізується на компонентах стартерів, генераторів та електроніки, популярний серед майстрів СТО." },
  { name: "Castrol", logo: "/Brands/Castrol.png", description: "Castrol — британський виробник мастил і технічних рідин, представлений у понад 150 країнах." },
  { name: "Cofle", logo: "/Brands/Cofle.png", description: "Cofle — італійський бренд із багаторічним досвідом у виробництві приводних тросів та гальмівних кабелів." },
  { name: "Continental", logo: "/Brands/Continental.png", description: "Continental — німецький гігант у сфері шин, електроніки та приводних систем для легкових і комерційних авто." },
  { name: "Corteco", logo: "/Brands/CORTECO.svg", description: "Corteco — бренд Freudenberg Group, пропонує високоякісні ущільнювачі, фільтри та антивібраційні компоненти." },
  { name: "Denso", logo: "/Brands/Denso.png", description: "Denso — японський виробник оригінальних свічок, компресорів і електроніки, постачальник для Toyota, Honda та ін." },
  { name: "Depo", logo: "/Brands/Depo.png", description: "Depo — тайванський бренд освітлювальних систем, відомий відмінною якістю альтернативного OEM-світла." },
  { name: "ELF", logo: "/Brands/ELF.png", description: "ELF — французький виробник мастил, що належить до TotalEnergies, популярний у мотоспорті та ралі." },
  { name: "Elring", logo: "/Brands/Elring.png", description: "Elring — німецький лідер у виробництві прокладок і ущільнювальних матеріалів для двигунів." },
  { name: "ERA", logo: "/Brands/ERA.png", description: "ERA — італійський бренд електронних компонентів і датчиків, що постачає на aftermarket ринок ЄС." },
  { name: "Facet", logo: "/Brands/Facet.png", description: "Facet — бренд, відомий своїми якісними датчиками, термостатами і контактними групами для легкових авто." },
  { name: "FAG", logo: "/Brands/FAG.png", description: "FAG — німецький виробник підшипників преміум-класу, який входить до складу Schaeffler Group." },
  { name: "Febest", logo: "/Brands/Febest.png", description: "Febest — німецько-японський бренд, що пропонує широкий асортимент деталей підвіски та кузова." },
  { name: "FEBI", logo: "/Brands/FEBI.png", description: "FEBI Bilstein — один з найстаріших європейських виробників запчастин для європейських, азійських та американських авто." },
  { name: "FERODO", logo: "/Brands/FERODO.png", description: "FERODO — британський бренд з більш ніж 100-річною історією в сфері фрикційних матеріалів і гальмівних систем." },
  { name: "FTE", logo: "/Brands/FTE.png", description: "FTE — німецький бренд, що спеціалізується на гідравлічних компонентах для гальмівних і зчепних систем." },
  { name: "Gates", logo: "/Brands/Gates.png", description: "Gates — провідний виробник приводних ременів, насосів та компонентів систем охолодження з США." },
  { name: "Goetze", logo: "/Brands/Goetze.png", description: "Goetze — бренд із понад 100-річною історією, що спеціалізується на поршневих кільцях і ущільненнях двигуна." },
  { name: "Hella", logo: "/Brands/Hella.png", description: "Hella — німецький гігант у виробництві освітлення та електроніки для легкових і вантажних авто." },
  { name: "INA", logo: "/Brands/INA.png", description: "INA — частина Schaeffler Group, що випускає підшипники, ролики та натяжні механізми високої точності." },
  { name: "INTELLI", logo: "/Brands/INTELLI.png", description: "INTELLI — американський бренд деталей підвіски, приводів і гумотехнічних елементів з високою стійкістю до зносу." },
  { name: "Kolbenschmidt", logo: "/Brands/Kolbenschmidt.png", description: "Kolbenschmidt — німецький виробник поршнів, вкладишів та компонентів для двигунів внутрішнього згоряння." },
  { name: "KYB", logo: "/Brands/KYB.webp", description: "KYB — японський бренд, один з найбільших у світі виробників амортизаторів та підвісок." },
  { name: "Lemförder",logo: "/Brands/Lemförder.png", description: "Lemförder — преміальний бренд ZF Group, що спеціалізується на компонентах рульового управління та підвіски." },
  { name: "Liqui Moly", logo: "/Brands/Liqui Moly.png", description: "Liqui Moly — німецький виробник мастил, присадок і автохімії з високими стандартами якості." },
  { name: "LUK", logo: "/Brands/LUK.png", description: "LUK — провідний виробник зчеплень і маховиків, частина Schaeffler Group, орієнтований на європейські авто." },
   { name: "MahleKnecht", logo: "/Brands/MahleKnecht.png", description: "Mahle — німецький інженерний гігант, відомий своїми фільтрами, поршнями, турбінами та деталями двигунів для OEM і aftermarket." },
   { name: "MANN-FILTER", logo: "/Brands/MANN-FILTER.png", description: "Німецький бренд преміум-класу, спеціалізується на високоякісних фільтрах для легкових, вантажних авто та промисловості." },
{ name: "Mobil", logo: "/Brands/Mobil.png", description: "Всесвітньо відомий бренд мастильних матеріалів, тісно асоціюється зі світом автоспорту та інноваційними технологіями." },
{ name: "MONROE", logo: "/Brands/MONROE.png", description: "Один із найбільших у світі виробників амортизаторів та підвісок, відомий надійністю та інноваціями." },
{ name: "NGK", logo: "/Brands/NGK.png", description: "Лідер у виробництві свічок запалювання та кисневих датчиків, популярний серед американських і японських автовиробників." },
{ name: "Nissens", logo: "/Brands/Nissens.png", description: "Данський бренд, що спеціалізується на системах охолодження та кондиціонування повітря, поєднує розкіш та інженерну досконалість." },
{ name: "OPTIMAL", logo: "/Brands/OPTIMAL.png", description: "Німецький виробник зосереджений на деталях підвіски, гальмівних системах та підшипниках, відомий європейською якістю." },
{ name: "Pierburg", logo: "/Brands/Pierburg.png", description: "Частина Rheinmetall Automotive, спеціалізується на системах подачі повітря, вакуумних насосах і компонентах ЕГР." },
{ name: "Quick Brake", logo: "/Brands/Quick Brake.png", description: "Датський виробник компонентів гальмівної системи, включаючи аксесуари та ремкомплекти, орієнтований на ефективність та безпеку." },
{ name: "Sachs", logo: "/Brands/Sachs.png", description: "Німецький бренд ZF Group, світовий лідер у виробництві зчеплень та амортизаторів для легкових і вантажних автомобілів." },
{ name: "Sidem", logo: "/Brands/Sidem.png", description: "Бельгійський виробник елементів рульового управління та підвіски з понад 85-річним досвідом, експортує продукцію по всьому світу." },
{ name: "Starline", logo: "/Brands/Starline.png", description: "Європейський бренд автозапчастин з широким асортиментом, орієнтований на доступну якість і надійність." },
{ name: "SKF", logo: "/Brands/SKF.png", description: "Шведський промисловий гігант, який спеціалізується на підшипниках, ущільненнях та вузлах для автомобільної та промислової галузей." },
{ name: "SNR", logo: "/Brands/SNR.png", description: "Французький бренд NTN-SNR, відомий інноваційними підшипниками та компонентами трансмісії для OEM та aftermarket." },
{ name: "Spidan", logo: "/Brands/Spidan.png", description: "Бренд GKN, спеціалізується на приводах, шарнірах та елементах підвіски, популярний у високопродуктивному сегменті." },
{ name: "SWAG", logo: "/Brands/SWAG.png", description: "Частина Bilstein Group, пропонує широкий асортимент автозапчастин, відомий точністю виготовлення та відповідністю OEM." },
{ name: "Textar", logo: "/Brands/Textar.png", description: "Провідний бренд гальмівних компонентів преміум-класу, постачальник на конвеєри провідних автовиробників." },
{ name: "TRW", logo: "/Brands/TRW.webp", description: "Частина ZF Group, лідер у розробці систем активної та пасивної безпеки: гальм, рульового керування та підвіски." },
{ name: "TYC", logo: "/Brands/TYC.png", description: "Німецький технологічний концерн з великим спектром автокомпонентів: електроніка, паливні системи, фільтри, освітлення та інше." },
{ name: "Valeo", logo: "/Brands/Valeo.png", description: "Французький виробник, один із лідерів у сфері кліматичних систем, зчеплень, освітлення та електроніки." },
{ name: "VDO - Continental", logo: "/Brands/VDO - Continental.png", description: "Німецький бренд в складі Continental, спеціалізується на автомобільних сенсорах, панелях приладів та електроніці." },
{ name: "Vernet", logo: "/Brands/Vernet.png", description: "Французький виробник термостатів і температурних сенсорів, відомий точністю та довговічністю." },
{ name: "VICTOR REINZ", logo: "/Brands/VICTOR REINZ.webp", description: "Бренд німецької компанії Dana Incorporated, спеціалізується на прокладках, ущільненнях та герметиках для двигунів." },
{ name: "ZF", logo: "/Brands/ZF.png", description: "Німецький концерн, світовий лідер у виробництві трансмісій, підвісок, зчеплень та елементів шасі." },

  // ===== Додаткові бренди =====
  { name: "MEYLE", logo: "/Brands/MEYLE.webp", description: "MEYLE — німецький виробник запчастин Хамбург, відомий підвищеною якістю деталей підвіски, рульового керування і гальмівних систем з маркуванням HD (Heavy Duty)." },
  { name: "DAYCO", logo: "/Brands/DAYCO.png", description: "DAYCO — американський виробник ременів, натяжних і паразитних роликів, гідравлічних компонентів. Постачальник OEM для провідних автовиробників." },
  { name: "MOOG", logo: "/Brands/MOOG.svg", description: "MOOG (Federal-Mogul / Tenneco) — американський бренд деталей підвіски і рульового керування преміум-класу, відомий кульовими опорами та наконечниками тяг." },
  { name: "DELPHI", logo: "/Brands/Delphi.svg", description: "Delphi Technologies — британський виробник компонентів паливних систем, запалювання, електроніки та систем керування двигуном." },
  { name: "FILTRON", logo: "/Brands/Filtron.svg", description: "FILTRON — польський виробник фільтрів (Mann+Hummel Group), пропонує широкий асортимент оливних, повітряних, паливних і салонних фільтрів." },
  { name: "PURFLUX", logo: "/Brands/Purflux.svg", description: "Purflux — французький виробник фільтрів із 1934 року, частина CLARCOR Inc. (Parker Hannifin), постачальник OEM для Peugeot, Citroën, Renault." },
  { name: "JC PREMIUM", logo: null, description: "JC Premium — польський виробник оригінальних замінників запчастин з широким каталогом деталей підвіски, двигуна і гальмівних систем." },
  { name: "TEKNOROT", logo: "/Brands/Teknorot.png", description: "TEKNOROT — турецький виробник деталей рульового керування та підвіски: важелів, наконечників і рульових тяг із широким покриттям марок." },
  { name: "ABE", logo: "/Brands/ABE.jpg", description: "ABE (C.S.Germany) — польська компанія, що виробляє запчастини підвіски, рульового і гальмівних систем під власною маркою ABE з суворим контролем якості." },
  { name: "MAXGEAR", logo: "/Brands/MAXGEAR.png", description: "MAXGEAR — польський виробник широкого асортименту запчастин: підвіска, гальма, двигун, система охолодження. Сертифікована продукція для авто всіх марок." },
  { name: "JP Group", logo: "/Brands/JP Group.png", description: "JP Group — датська компанія з 1962 року, постачає запчастини для Volkswagen Group, BMW, Mercedes, Ford та японських марок у Скандинавії і Європі." },
  { name: "RUVILLE", logo: "/Brands/Ruville.png", description: "RUVILLE — бренд Schaeffler Group, спеціалізується на підшипниках ступиці, роликах натяжників і компонентах трансмісії OEM-якості." },
  { name: "JAPANPARTS", logo: "/Brands/JAPANPARTS.jpg", description: "JAPANPARTS — італійська торгова марка, що спеціалізується на запчастинах для японських і корейських авто: Toyota, Honda, Nissan, Hyundai, Kia." },
  { name: "SASIC", logo: "/Brands/SASIC.png", description: "SASIC — французький виробник деталей підвіски, ШРУСів, опор амортизаторів і підшипникових вузлів для широкого спектру авто." },
  { name: "HANS PRIES", logo: "/Brands/HANS PRIES.svg", description: "Hans Pries (HP Autozubehör) — австрійська компанія, яка постачає запчастини для широкого кола марок авто в Центральній і Східній Європі." },
  { name: "PASCAL", logo: "/Brands/PASCAL.jpg", description: "PASCAL — польський виробник деталей гальмівної системи та рульового керування для легкових і комерційних авто." },
  { name: "REINHOCH", logo: "/Brands/REINHOCH.jpg", description: "REINHOCH — іспанський бренд (RH Group), пропонує запчастини підвіски і рульового керування з відповідністю стандартам OEM." },
  { name: "TERMOTEC", logo: "/Brands/TERMOTEC.png", description: "TERMOTEC — польський виробник компонентів системи охолодження двигуна: радіаторів, помп, термостатів і патрубків." },
  { name: "BTA", logo: "/Brands/BTA.jpg", description: "BTA — польська торгова марка запчастин із потужним покриттям деталей підвіски, гальм і системи охолодження для популярних марок авто." },
  { name: "MAGNUM", logo: "/Brands/MAGNUM.jpg", description: "Magnum Technology — польський виробник амортизаторів, пружин підвіски і відповідних аксесуарів для легкових та комерційних авто." },
  { name: "FORTUNE", logo: "/Brands/FORTUNE.png", description: "Fortune — тайванський виробник гумотехнічних запчастин: пильників, сайлентблоків і ущільнювачів для широкого кола авто." },
  { name: "SOLGY", logo: "/Brands/SOLGY.svg", description: "SOLGY — іспанський виробник деталей підвіски і рульового керування, відомий точністю виготовлення та відповідністю OEM-специфікаціям." },
  { name: "Adriauto", logo: "/Brands/Adriauto.jpg", description: "Adriauto — італійський виробник запчастин з великим асортиментом деталей для двигуна, підвіски і кузова переважно для авто 1990-2010 років." },
  { name: "ALPHA", logo: null, description: "ALPHA (Alpha Autoteile) — виробник гумотехнічних деталей і компонентів підвіски для популярних марок авто в Східній Європі." },
  { name: "WUNDER", logo: "/Brands/WUNDER.webp", description: "WUNDER — турецький виробник деталей рульового керування та підвіски, активно представлений на авторинку Центральної і Східної Євпропи." },
  { name: "CAVO", logo: "/Brands/CAVO.jpg", description: "CAVO — виробник тросів і кабелів для систем зчеплення, ручного гальма і педальних механізмів авто різних марок і моделей." },
  { name: "AUTOTECHTEILE", logo: "/Brands/AUTOTECHTEILE.svg", description: "Autotechteile — польський виробник широкого асортименту запчастин підвіски та рульового керування для авто марок VAG, BMW, Mercedes та ін." },
  { name: "Linex", logo: "/Brands/Linex.png", description: "Linex — шведська компанія з 1958 року, що виробляє тросики та кабелі для газу, зчеплення і ручного гальма для широкого спектру авто." },
  { name: "IMPERGOM", logo: "/Brands/IMPERGOM.svg", description: "IMPERGOM — італійський виробник гумових деталей підвіски: втулок, подушок і пружинних відбійників для легкових авто." },
  { name: "Seiken", logo: "/Brands/Seiken.png", description: "Seiken — японський виробник гальмівних компонентів і деталей гідравлічних систем. Постачальник OEM для японських авто." },
  { name: "NTY", logo: "/Brands/NTY.png", description: "NTY — польський виробник широкого асортименту запчастин: підвіска, рульове, гальма, двигун. Відомий доступною якістю для масового сегменту." },
  { name: "KRONSO", logo: null, description: "KRONSO — виробник деталей підвіски та рульового керування з широким покриттям для авто Volkswagen Group, Ford, Opel та інших марок." },
  { name: "RIDER", logo: "/Brands/RIDER.webp", description: "RIDER — виробник пружин підвіски і відповідних аксесуарів для легкових авто, орієнтований на ринок Центральної та Східної Європи." },
  { name: "GOODREM", logo: "/Brands/GOODREM.webp", description: "GOODREM — виробник гумових і гумово-металевих деталей підвіски: сайлентблоків, втулок і подушок двигуна." },
  { name: "UCEL", logo: "/Brands/UCEL.jpg", description: "UCEL — турецький виробник гумотехнічних запчастин підвіски та двигуна, активний на ринку Туреччини та Центральної Азії." },
  { name: "ASAM-SA", logo: "/Brands/ASAM-SA.webp", description: "ASAM-SA — румунський виробник запчастин з широким асортиментом для Dacia, Renault та інших марок, розповсюджених у Східній Євпропі." },
  { name: "WIX", logo: "/Brands/WIX.svg", description: "WIX Filters (Dana Inc.) — американський виробник фільтрів із 1939 року, пропонує оливні, паливні, повітряні та гідравлічні фільтри для легкових і вантажних авто." },
  { name: "Victor Reinz", logo: "/Brands/VICTOR REINZ.webp", description: "Victor Reinz (Dana Inc.) — провідний виробник прокладок двигуна, комплектів ущільнень ГБЦ та герметиків для двигунів усіх типів." },
  { name: "Continental AG", logo: "/Brands/Continental.png", description: "Continental AG — глобальний автомобільний постачальник: шини, електроніка, системи приводу та компоненти гальмівних систем для OEM і aftermarket." },
  { name: "KNECHT", logo: "/Brands/MANN-FILTER.png", description: "KNECHT — торгова марка Mahle для фільтрів масла, повітря, палива і салону. Синонім якості фільтрації на европейському ринку з 1927 року." },
  { name: "LEMFORDER", logo: "/Brands/Lemförder.png", description: "Lemförder (ZF Group) — преміальний виробник компонентів рульового керування та підвіски з найвищим рівнем точності виготовлення." },

  // ===== Розширений список брендів =====
  { name: "ATE", logo: "/Brands/ATE.webp", description: "ATE (Continental) — провідний виробник гальмівних систем і компонентів; постачальник OEM для Mercedes, BMW, Audi та ін." },
  { name: "MAHLE", logo: "/Brands/MAHLE.png", description: "MAHLE — німецький інженерний гігант: поршні, фільтри, турбіни, термостати та компоненти двигуна для OEM і aftermarket." },
  { name: "KAYABA", logo: "/Brands/KAYABA.svg", description: "KAYABA (KYB) — японський виробник амортизаторів і підвісок, один з лідерів ринку для легкових і комерційних авто." },
  { name: "KAMOKA", logo: "/Brands/KAMOKA.png", description: "KAMOKA — польський виробник фільтрів і компонентів підвіски, орієнтований на широкий aftermarket ринок Центральної та Східної Європи." },
  { name: "CHAMPION", logo: "/Brands/CHAMPION.png", description: "Champion (Federal-Mogul) — американський виробник свічок запалювання, фільтрів і компонентів систем запалювання для авто різних марок." },
  { name: "BERU", logo: "/Brands/BERU.svg", description: "BERU (NGK Group) — провідний виробник свічок розжарювання, свічок запалювання і сенсорних компонентів для дизельних і бензинових двигунів." },
  { name: "BLUE PRINT", logo: "/Brands/BLUE PRINT.webp", description: "Blue Print (Alliance Automotive Group) — широкий асортимент запчастин для японських і корейських авто: фільтри, гальма, підвіска, двигун." },
  { name: "CONTITECH", logo: "/Brands/CONTITECH.svg", description: "ContiTech (Continental) — виробник ременів ГРМ, клинових ременів, шлангів і компонентів системи охолодження OEM-якості." },
  { name: "DENCKERMANN", logo: "/Brands/DENCKERMANN.webp", description: "Denckermann — польський виробник фільтрів і гальмівних компонентів для широкого спектру легкових авто з відповідністю OEM-стандартам." },
  { name: "CIFAM", logo: "/Brands/CIFAM.png", description: "CIFAM — португальський виробник гальмівних колодок і дисків, популярний серед профільних СТО завдяки якості за доступною ціною." },
  { name: "NK", logo: "/Brands/NK.svg", description: "NK — данський бренд гальмівних компонентів: колодки, диски та аксесуари для широкого кола легкових і комерційних авто." },
  { name: "LPR", logo: "/Brands/LPR.webp", description: "LPR (Lucas Premium Racing) — італійський виробник гальмівних колодок, дисків і компонентів гідравлічних гальм преміум-класу." },
  { name: "METELLI", logo: "/Brands/METELLI.png", description: "Metelli — італійський виробник компонентів гальмівної системи та зчеплення, постачальник OEM для провідних автовиробників з 1965 року." },
  { name: "NTN", logo: "/Brands/NTN.png", description: "NTN — японський виробник підшипників і підшипникових вузлів для легкових авто, частина альянсу NTN-SNR." },
  { name: "DOLZ", logo: "/Brands/DOLZ.jpg", description: "DOLZ — іспанський виробник водяних насосів з 1934 року; широка лінійка для OEM і aftermarket ринків по всьому світу." },
  { name: "TOPRAN", logo: "/Brands/TOPRAN.svg", description: "TOPRAN — голландський бренд широкого асортименту запчастин: підвіска, рульове, кузов і двигун для авто марок VAG, BMW, Ford та ін." },
  { name: "METZGER", logo: "/Brands/METZGER.svg", description: "Metzger — австрійський виробник запчастин для підвіски, рульового керування та кузова з широким покриттям марок авто." },
  { name: "MAGNETI MARELLI", logo: "/Brands/MAGNETI MARELLI.webp", description: "Magneti Marelli (Marelli Holdings) — італійський виробник електронних систем, освітлення, сенсорів і компонентів двигуна для OEM і aftermarket." },
  { name: "MASTER-SPORT", logo: "/Brands/MASTER-SPORT.png", description: "Master-Sport — чеський виробник широкого асортименту запчастин: гальма, підвіска, рульове, двигун. Відомий доступною якістю на ринку Центральної Європи." },
  { name: "HENGST FILTER", logo: "/Brands/HENGST FILTER.svg", description: "Hengst Filter — німецький виробник фільтрів і компонентів очищення повітря, масла та палива з більш ніж 60-річним досвідом." },
  { name: "THERMOTEC", logo: "/Brands/THERMOTEC.png", description: "Thermotec — польський виробник компонентів системи охолодження: радіаторів, інтеркулерів, вентиляторів і патрубків для широкого кола авто." },
  { name: "VEMO", logo: "/Brands/VEMO.png", description: "VEMO — бренд для електричних і електронних компонентів авто: датчики, реле, перемикачі, кабелі для легкових і комерційних авто." },
  { name: "STELLOX", logo: "/Brands/STELLOX.svg", description: "Stellox — польський виробник запчастин підвіски та рульового керування, відомий якісним покриттям для авто марок VAG, BMW, Mercedes та ін." },
  { name: "LESJOFORS", logo: "/Brands/LESJOFORS.svg", description: "Lesjofors — шведський виробник пружин підвіски та стабілізаторів з 1852 року; постачальник OEM-якості для широкого кола авто." },
  { name: "HEPU", logo: "/Brands/HEPU.png", description: "HEPU — польський виробник водяних насосів, термостатів і компонентів системи охолодження двигуна для широкого спектру марок авто." },
  { name: "BOSAL", logo: "/Brands/BOSAL.png", description: "Bosal — бельгійський виробник вихлопних систем, каталізаторів і систем випуску для легкових і комерційних авто з OEM-відповідністю." }
];
