export const brands = [
  { name: "Airtex", logo: "/Brands/Airtex.png", description: "Airtex — німецький бренд, що спеціалізується на високоякісних водяних насосах і компонентах систем охолодження для легкових та вантажних авто." },
  { name: "Alkar", logo: "/Brands/Alkar.png", description: "Alkar — іспанський виробник дзеркал, освітлення та елементів кузова, відомий якістю продукції для спортивних і серійних авто." },
  { name: "Autofren Seinsa", logo: "/Brands/Autofren Seinsa.png", description: "Autofren Seinsa — один з найбільших світових постачальників ремкомплектів гальмівних систем, з потужним виробництвом у Європі." },
  { name: "BCGUMA", logo: "/Brands/BCGUMA.png", description: "BCGUMA — американський виробник гумотехнічних виробів, зокрема пильовиків і сальників, популярний у класичних моделях." },
  { name: "Bilstein",logo: "/Brands/Bilstein.png", description: "Bilstein — німецький лідер у виробництві преміальних амортизаторів і підвісок, широко використовується в автоспорті." },
  { name: "Bosch", logo: "/Brands/Bosch.png", description: "Bosch — глобальний концерн із Німеччини, що виробляє широкий спектр автозапчастин: від електроніки до гальмівних систем." },
  { name: "Brembo", logo: "/Brands/Brembo.png", description: "Brembo — італійський бренд №1 у сфері гальмівних систем, використовується в преміальних і спортивних авто." },
  { name: "CARGO", logo: "/Brands/CARGO.png", description: "CARGO — спеціалізується на компонентах стартерів, генераторів та електроніки, популярний серед майстрів СТО." },
  { name: "Castrol", logo: "/Brands/Castrol.png", description: "Castrol — британський виробник мастил і технічних рідин, представлений у понад 150 країнах." },
  { name: "Cofle", logo: "/Brands/Cofle.png", description: "Cofle — італійський бренд із багаторічним досвідом у виробництві приводних тросів та гальмівних кабелів." },
  { name: "Continental", logo: "/Brands/Continental.png", description: "Continental — німецький гігант у сфері шин, електроніки та приводних систем для легкових і комерційних авто." },
  { name: "Corteco", logo: "/Brands/Corteco.png", description: "Corteco — бренд Freudenberg Group, пропонує високоякісні ущільнювачі, фільтри та антивібраційні компоненти." },
  { name: "Denso", logo: "/Brands/Denso.png", description: "Denso — японський виробник оригінальних свічок, компресорів і електроніки, постачальник для Toyota, Honda та ін." },
  { name: "Depo", logo: "/Brands/Depo.png", description: "Depo — тайванський бренд освітлювальних систем, відомий відмінною якістю альтернативного OEM-світла." },
  { name: "ELF", logo: "/Brands/ELF.png", description: "ELF — французький виробник мастил, що належить до TotalEnergies, популярний у мотоспорті та ралі." },
  { name: "Elring", logo: "/Brands/Elring.png", description: "Elring — німецький лідер у виробництві прокладок і ущільнювальних матеріалів для двигунів." },
  { name: "ERA", logo: "/Brands/ERA.png", description: "ERA — італійський бренд електронних компонентів і датчиків, що постачає на aftermarket ринок ЄС." },
  { name: "Facet", logo: "/Brands/Facet.png", description: "Facet — бренд, відомий своїми якісними датчиками, термостатами і контактними групами для легкових авто." },
  { name: "FAG", logo: "/Brands/FAG.png", description: "FAG — німецький виробник підшипників преміум-класу, який входить до складу Schaeffler Group." },
  { name: "Febest", logo: "/Brands/Febest.png", description: "Febest — німецько-японський бренд, що пропонує широкий асортимент деталей підвіски та кузова." },
  { name: "FEBI", logo: "/Brands/FEBI.png", description: "FEBI Bilstein — один з найстаріших європейських виробників запчастин для європейських, азійських та американських авто." },
  { name: "FERODO", logo: "/Brands/FERODO.png", description: "FERODO — британський бренд з більш ніж 100-річною історією в сфері фрикційних матеріалів і гальмівних систем." },
  { name: "FTE", logo: "/Brands/FTE.png", description: "FTE — німецький бренд, що спеціалізується на гідравлічних компонентах для гальмівних і зчепних систем." },
  { name: "Gates", logo: "/Brands/Gates.png", description: "Gates — провідний виробник приводних ременів, насосів та компонентів систем охолодження з США." },
  { name: "Goetze", logo: "/Brands/Goetze.png", description: "Goetze — бренд із понад 100-річною історією, що спеціалізується на поршневих кільцях і ущільненнях двигуна." },
  { name: "Hella", logo: "/Brands/Hella.png", description: "Hella — німецький гігант у виробництві освітлення та електроніки для легкових і вантажних авто." },
  { name: "INA", logo: "/Brands/INA.png", description: "INA — частина Schaeffler Group, що випускає підшипники, ролики та натяжні механізми високої точності." },
  { name: "INTELLI", logo: "/Brands/INTELLI.png", description: "INTELLI — американський бренд деталей підвіски, приводів і гумотехнічних елементів з високою стійкістю до зносу." },
  { name: "Kolbenschmidt", logo: "/Brands/Kolbenschmidt.png", description: "Kolbenschmidt — німецький виробник поршнів, вкладишів та компонентів для двигунів внутрішнього згоряння." },
  { name: "KYB", logo: "/Brands/KYB.png", description: "KYB — японський бренд, один з найбільших у світі виробників амортизаторів та підвісок." },
  { name: "Lemförder",logo: "/Brands/Lemförder.png", description: "Lemförder — преміальний бренд ZF Group, що спеціалізується на компонентах рульового управління та підвіски." },
  { name: "Liqui Moly", logo: "/Brands/Liqui Moly.png", description: "Liqui Moly — німецький виробник мастил, присадок і автохімії з високими стандартами якості." },
  { name: "LUK", logo: "/Brands/LUK.png", description: "LUK — провідний виробник зчеплень і маховиків, частина Schaeffler Group, орієнтований на європейські авто." },
   { name: "MahleKnecht", logo: "/Brands/MahleKnecht.png", description: "Mahle — німецький інженерний гігант, відомий своїми фільтрами, поршнями, турбінами та деталями двигунів для OEM і aftermarket." },
   { name: "MANN-FILTER", logo: "/Brands/MANN-FILTER.png", description: "Німецький бренд преміум-класу, спеціалізується на високоякісних фільтрах для легкових, вантажних авто та промисловості." },
{ name: "Mobil", logo: "/Brands/Mobil.png", description: "Всесвітньо відомий бренд мастильних матеріалів, тісно асоціюється зі світом автоспорту та інноваційними технологіями." },
{ name: "MONROE", logo: "/Brands/MONROE.png", description: "Один із найбільших у світі виробників амортизаторів та підвісок, відомий надійністю та інноваціями." },
{ name: "NGK", logo: "/Brands/NGK.png", description: "Лідер у виробництві свічок запалювання та кисневих датчиків, популярний серед американських і японських автовиробників." },
{ name: "Nissens", logo: "/Brands/Nissens.png", description: "Данський бренд, що спеціалізується на системах охолодження та кондиціонування повітря, поєднує розкіш та інженерну досконалість." },
{ name: "OPTIMAL", logo: "/Brands/OPTIMAL.png", description: "Німецький виробник зосереджений на деталях підвіски, гальмівних системах та підшипниках, відомий європейською якістю." },
{ name: "Pierburg", logo: "/Brands/Pierburg.png", description: "Частина Rheinmetall Automotive, спеціалізується на системах подачі повітря, вакуумних насосах і компонентах ЕГР." },
{ name: "Quick Brake", logo: "/Brands/Quick Brake.png", description: "Датський виробник компонентів гальмівної системи, включаючи аксесуари та ремкомплекти, орієнтований на ефективність та безпеку." },
{ name: "Sachs", logo: "/Brands/Sachs.png", description: "Німецький бренд ZF Group, світовий лідер у виробництві зчеплень та амортизаторів для легкових і вантажних автомобілів." },
{ name: "Sidem", logo: "/Brands/Sidem.png", description: "Бельгійський виробник елементів рульового управління та підвіски з понад 85-річним досвідом, експортує продукцію по всьому світу." },
{ name: "Starline", logo: "/Brands/Starline.png", description: "Європейський бренд автозапчастин з широким асортиментом, орієнтований на доступну якість і надійність." },
{ name: "SKF", logo: "/Brands/SKF.png", description: "Шведський промисловий гігант, який спеціалізується на підшипниках, ущільненнях та вузлах для автомобільної та промислової галузей." },
{ name: "SNR", logo: "/Brands/SNR.png", description: "Французький бренд NTN-SNR, відомий інноваційними підшипниками та компонентами трансмісії для OEM та aftermarket." },
{ name: "Spidan", logo: "/Brands/Spidan.png", description: "Бренд GKN, спеціалізується на приводах, шарнірах та елементах підвіски, популярний у високопродуктивному сегменті." },
{ name: "SWAG", logo: "/Brands/SWAG.png", description: "Частина Bilstein Group, пропонує широкий асортимент автозапчастин, відомий точністю виготовлення та відповідністю OEM." },
{ name: "Textar", logo: "/Brands/Textar.png", description: "Провідний бренд гальмівних компонентів преміум-класу, постачальник на конвеєри провідних автовиробників." },
{ name: "TRW", logo: "/Brands/TRW.png", description: "Частина ZF Group, лідер у розробці систем активної та пасивної безпеки: гальм, рульового керування та підвіски." },
{ name: "TYC", logo: "/Brands/TYC.png", description: "Німецький технологічний концерн з великим спектром автокомпонентів: електроніка, паливні системи, фільтри, освітлення та інше." },
{ name: "Valeo", logo: "/Brands/Valeo.png", description: "Французький виробник, один із лідерів у сфері кліматичних систем, зчеплень, освітлення та електроніки." },
{ name: "VDO - Continental", logo: "/Brands/VDO - Continental.png", description: "Німецький бренд в складі Continental, спеціалізується на автомобільних сенсорах, панелях приладів та електроніці." },
{ name: "Vernet", logo: "/Brands/Vernet.png", description: "Французький виробник термостатів і температурних сенсорів, відомий точністю та довговічністю." },
{ name: "VICTOR REINZ", logo: "/Brands/VICTOR REINZ.png", description: "Бренд німецької компанії Dana Incorporated, спеціалізується на прокладках, ущільненнях та герметиках для двигунів." },
{ name: "ZF", logo: "/Brands/ZF.png", description: "Німецький концерн, світовий лідер у виробництві трансмісій, підвісок, зчеплень та елементів шасі." }

  // ➕ додайте більше брендів за потреби
];
