// carBrands.ts
export interface CarBrand {
  id: number;
  name: string;
  logo: string;
  models?: string[]; // При бажанні одразу додати моделі
}

export const carBrands: CarBrand[] = [
  { id: 1, name: "AUDI", logo: "/Carlogo/Audi.svg" },
  { id: 2, name: "BMW", logo: "/Carlogo/BMW.svg" },
  { id: 3, name: "CHERY", logo: "/Carlogo/Chery.svg" },
  { id: 4, name: "CHRYSLER", logo: "/Carlogo/Chrysler.svg" },
  { id: 5, name: "CITROEN", logo: "/Carlogo/Citroen.svg" },
  { id: 6, name: "CADILLAC", logo: "/Carlogo/Cadillac.svg" },
  { id: 7, name: "DACIA", logo: "/Carlogo/Dacia.svg" },
  { id: 8, name: "DAEWOO", logo: "/Carlogo/Daewoo.svg" },
  { id: 9, name: "DAF", logo: "/Carlogo/DAF.svg" },
  { id: 10, name: "DODGE", logo: "/Carlogo/Dodge.svg" },
  { id: 11, name: "FERRARI", logo: "/Carlogo/Ferrari.svg" },
  { id: 12, name: "FIAT", logo: "/Carlogo/Fiat.svg" },
  { id: 13, name: "FORD", logo: "/Carlogo/Ford.svg" },
  { id: 14, name: "CHEVROLET", logo: "/Carlogo/Chevrolet.svg" },
  { id: 15, name: "GEELY", logo: "/Carlogo/Geely.svg" },
  { id: 16, name: "HONDA", logo: "/Carlogo/Honda.svg" },
  { id: 17, name: "HUMMER", logo: "/Carlogo/Hummer.svg" },
  { id: 18, name: "HYUNDAI", logo: "/Carlogo/Hyunndai.svg" },
  { id: 19, name: "INFINITI", logo: "/Carlogo/Infiniti.svg" },
  { id: 20, name: "ISUZU", logo: "/Carlogo/Isuzu.svg" },
  { id: 21, name: "IVECO", logo: "/Carlogo/Iveco.svg" },
  { id: 22, name: "JAGUAR", logo: "/Carlogo/Jaguar.svg" },
  { id: 23, name: "JEEP", logo: "/Carlogo/Jeep.svg" },
  { id: 24, name: "KIA", logo: "/Carlogo/KIA.svg" },
  { id: 25, name: "LADA", logo: "/Carlogo/Lada.svg" },
  { id: 26, name: "LAMBORGHINI", logo: "/Carlogo/Lamborghini.svg" },
  { id: 27, name: "LANCIA", logo: "/Carlogo/Lancia.svg" },
  { id: 28, name: "LAND ROVER", logo: "/Carlogo/Landrover.svg" },
  { id: 29, name: "LEXUS", logo: "/Carlogo/Lexus.svg" },
  { id: 30, name: "LINCOLN", logo: "/Carlogo/Lincoln.svg" },
  { id: 31, name: "LOTUS", logo: "/Carlogo/Lotus.svg" },
  { id: 32, name: "MAN", logo: "/Carlogo/Man.svg" },
  { id: 33, name: "MASERATI", logo: "/Carlogo/Maserati.svg" },
  { id: 34, name: "MAYBACH", logo: "/Carlogo/Maybach.webp" },
  { id: 35, name: "MAZDA", logo: "/Carlogo/Mazda.svg" },
  { id: 36, name: "MERCEDES-BENZ", logo: "/Carlogo/Mercedes.webp" },
  { id: 37, name: "MINI", logo: "/Carlogo/Mini.svg" },
  { id: 38, name: "MITSUBISHI", logo: "/Carlogo/Mitsubishi.svg" },
  { id: 39, name: "NISSAN", logo: "/Carlogo/Nissan.svg" },
  { id: 40, name: "OPEL", logo: "/Carlogo/Opel.svg" },
  { id: 41, name: "PEUGEOT", logo: "/Carlogo/Peugeot.svg" },
  { id: 42, name: "PONTIAC", logo: "/Carlogo/Pontiac.svg" },
  { id: 43, name: "PORSCHE", logo: "/Carlogo/Porsche.webp" },
  { id: 44, name: "RAM", logo: "/Carlogo/Ram.svg" },
  { id: 45, name: "RENAULT", logo: "/Carlogo/Renault.svg" },
  { id: 46, name: "ROLLS-ROYCE", logo: "/Carlogo/Rollsroyce.svg" },
  { id: 47, name: "ROVER", logo: "/Carlogo/Rover.svg" },
  { id: 48, name: "SAAB", logo: "/Carlogo/Saab.svg" },
  { id: 49, name: "SEAT", logo: "/Carlogo/Seat.webp" },
  { id: 50, name: "SKODA", logo: "/Carlogo/Skoda.webp" },
  { id: 51, name: "SMART", logo: "/Carlogo/Smart.svg" },
  { id: 52, name: "SSANGYONG", logo: "/Carlogo/Ssangyong.svg" },
  { id: 53, name: "SUBARU", logo: "/Carlogo/Subaru.webp" },
  { id: 54, name: "SUZUKI", logo: "/Carlogo/Suzuki.svg" },
  { id: 55, name: "TESLA", logo: "/Carlogo/Tesla.svg" },
  { id: 56, name: "TOYOTA", logo: "/Carlogo/Toyota.svg" },
  { id: 57, name: "VOLVO", logo: "/Carlogo/Volvo.svg" },
  { id: 58, name: "VOLKSWAGEN", logo: "/Carlogo/Volkswagen.svg" },
  { id: 59, name: "ACURA", logo: "/Carlogo/Acura.svg" },
  { id: 60, name: "ALFA ROMEO", logo: "/Carlogo/Alfaromeo.webp" },
  { id: 61, name: "ASTON MARTIN", logo: "/Carlogo/Astonmartin.webp" },
  { id: 62, name: "BENTLEY", logo: "/Carlogo/Bentley.svg" },
];
